# render.yaml - GenPlay Studio 3D Deployment Configuration

services:
  # Static site (React app)
  - type: web
    name: genplay-studio-3d
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    envVars:
      - key: VITE_TRIPO_AI_API_KEY
        sync: false
      - key: VITE_RENDER_PROXY_URL
        value: https://genplay-proxy.onrender.com
      - key: NODE_ENV
        value: production

  # Proxy service (for API calls)
  - type: web
    name: genplay-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node proxy-server.js
    envVars:
      - key: VITE_TRIPO_AI_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 